<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/data/Data_Analysis.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>

# Kata: Data Analysis

Inspired by an activity in the [Open Machine Learning Course](https://mlcourse.ai/).

## Instructions

This is a self-correcting exercise generated by [nbgrader](https://github.com/jupyter/nbgrader). 

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.

## Part 1 : Loading data

In [1]:
# Import required libraries
import numpy as np
import pandas as pd

### Question

Use Pandas to load the dataset located [here](https://raw.githubusercontent.com/bpesquet/machine-learning-handbook/master/datasets/athlete_events.csv), which was extracted from this [Kaggle competition](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results/). Store it into a DataFrame named `df_olympics`.

In [6]:
# YOUR CODE HERE
df_olympics = pd.read_csv("athlete_events.csv")
df_olympics.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [7]:
print(f'df_olympics: {df_olympics.shape}')
assert isinstance(df_olympics, pd.DataFrame)
assert df_olympics.shape == (271116, 15)

df_olympics: (271116, 15)

## Part 2: Exploring data

### Question

Print general information about the DataFrame.

In [8]:
# YOUR CODE HERE
df_olympics.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

### Question

Print and observe the first 10 records of the dataset.

In [9]:
# YOUR CODE HERE
df_olympics.head(10)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN

### Question

Print and observe 5 random records of the dataset.

In [10]:
# YOUR CODE HERE
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
262293,131239,Jrg Woithe,M,17.0,194.0,80.0,East Germany,GDR,1980 Summer,1980,Summer,Moskva,Swimming,Swimming Men's 4 x 200 metres Freestyle Relay,Silver
20314,10716,Natlia Maria Bernardo,F,21.0,170.0,65.0,Angola,ANG,2008 Summer,2008,Summer,Beijing,Handball,Handball Women's Handball,NaN
223002,112004,Nanne Pieter Sluis,M,29.0,193.0,88.0,Netherlands,NED,2012 Summer,2012,Summer,London,Rowing,Rowing Men's Coxless Pairs,NaN
217187,109090,Kylie Noele Shadbolt,F,19.0,NaN,NaN,Australia,AUS,1992 Summer,1992,Summer,Barcelona,Gymnastics,Gymnastics Women's Horse Vault,NaN
54368,27896,Georges Henri Dtreille,M,26.0,NaN,NaN,France,FRA,1920 Summer,1920,Summer,Antwerpen,Cycling,"Cycling Men's Road Race, Team",Gold